# Generated by Django 3.2.8 on 2021-11-05 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawings',
            options={'managed': False},
        ),
    ]
