# Generated by Django 3.2.8 on 2021-11-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_drawings_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drawings',
            options={'managed': True},
        ),
    ]
