# Generated by Django 3.2.8 on 2021-11-07 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_drawings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawings',
            name='content',
            field=models.CharField(max_length=131070),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=32767)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.drawings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
